### ISSUE TITLE
the real g(x)

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/derivative-chain-rule#1]
You say here:

> Remember we started with the function  f(x)=(.5x+3)^2. Then we used functional composition to split this into two.
> 
> g(x)=x2 
> f(x)=(g(x))^2

So shouldn't

> g(x)=x^2

be instead

g(x)=.5x+3

?

And further below, you say:

> Then substituting for  g(x) , which we already defined:
> 
> f′(g(x))=g(x)=x^2 
> So the derivative of the function  f(x)=(.5x+3)^2 is  f′(x)=x^2

But if 
g(x)=.5x+3
shouldn't 
f′(x)=.5x+3
?

If I am wrong about this (entirely possible), I might suggest you expound on the origins of g(x)=x^2

**Comment by EricMa206** [comment]
Noticed the same thing. The correct derivative to (0.5x+3)^2 is 0.5x+3. 
Please fix.

**Comment by mas16** [comment]
Thanks annieeby and EricMa206, this has been corrected.
