### ISSUE TITLE
The 'name' of the f(x) and g(x) functions on the first plot is the wrong way round

### ISSUE THREAD

**Issue by isobeldaley** [learn-co-curriculum/derivative-chain-rule#5]
<img width="1116" alt="Screenshot 2019-07-06 at 10 48 22" src="https://user-images.githubusercontent.com/47493551/60754044-d0212c80-9fdb-11e9-874d-2bbd74ecc112.png">

**Comment by mas16** [comment]
Thanks isobeldaley, this has been corrected.
